import ProfileSidebar from '@/Components/ProfileSidebar/ProfileSidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Orbitron  } from 'next/font/google'
import ChatSidebar from '@/Components/ChatSidebar/ChatSidebar'
import Head from 'next/head'
import Script from 'next/script'
import SearchComponent from '@/Components/Search'

const orbitron = Orbitron({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'BioLink',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">    
      <body className={`${orbitron.className} text-white`} suppressHydrationWarning={true}>
        <div className="flex min-h-screen duration-300">

          <ProfileSidebar />

          <div className="w-8/12">
            <SearchComponent />
            {children}
          </div>

          <ChatSidebar />

        </div>
      </body>
    </html>
  )
}
